### ISSUE TITLE
SOC is 1 and Vbatt 8.2V

### ISSUE THREAD

**Issue by toopazo** [proyectoSuchai/SUCHAI#11]
SOC is 1 and Vbatt 8.2V instead of 8/9 it should be

**Comment by carlgonz** [comment]
Se ha visto algo de este bug @toopazo ?

**Comment by toopazo** [comment]
No, aun no. Cuando integremos lo resolveremos.

*Tomás Opazo T.*
Electrical engineer
http://spel.ing.uchile.cl/
cel: +56951214672


2015-01-06 11:07 GMT-03:00 Carlos <notifications@github.com>:

**Comment by carlgonz** [comment]
Ya no correspode debido al cambio de EPS
