### ISSUE TITLE
dat_pay_expFis causing reset

### ISSUE THREAD

**Issue by carlgonz** [proyectoSuchai/SUCHAI#14]
Debug trace:

[Houskeeping] 20[s] actions..
[FlightPlan2] _4sec_check
[Dispatcher] Orig: 0x1105 | Cmd: 0x6001 | Param: 8
  FSM_default => pay_i = dat_pay_expFis
    fis_iterate..
    len( ADC_period[] )\0xff\0x00\0x00\0x00\0x00\0x00\0x00\0x00\0x00\0x00\0x00
--------- SUCHAI BOOT SEQUENCE ---------
.....

**Comment by carlgonz** [comment]
Que hay de este bug? Se puede cerrar el issue?

**Comment by toopazo** [comment]
The bug was fixed.
