### ISSUE TITLE
Replace SD memory

### ISSUE THREAD

**Issue by carlgonz** [proyectoSuchai/SUCHAI#16]
Use SD not microSD

**Comment by carlgonz** [comment]
Se compraron sd nuevas

**Comment by toopazo** [comment]
Se instalaron y funcionaron correctamente.
Slds

*Tomás Opazo T.*
Electrical engineer
http://spel.ing.uchile.cl/
cel: +56951214672


2015-01-06 11:06 GMT-03:00 Carlos <notifications@github.com>:
