### ISSUE TITLE
Fundir FP y FP2 en una sola tarea y probar que no haya StackOverflow

### ISSUE THREAD

**Issue by toopazo** [proyectoSuchai/SUCHAI#21]
Fundir FP y FP2 en una sola tarea y probar que no haya StackOverflow.
Posterior a ello probar que los comandos en FP se ejecuten en los horarios correspondientes.

**Comment by toopazo** [comment]
Resuelto

Implementado a traves del comando int drp_fpl_check_and_exec(void *param) El cual se llama perdicamente desde FP3. FP3 es la nueva tarea que revisa el itinerario y ademas ejecuta payloads.

Ahora, en SUCHAI_config.h se puede escoger entre 3 opciones de FP, variable SCH_FLIGHTPLAN_TYPE.
tarea FP (a secas): revisa y ejecuta el itinerario a traves del comando drp_fpl_check_and_exec.
tarea FP2: Ejecuta periodicamente payloads a traves del comando pay_fp2_default_fsm.
tarea FP3: Realiza ambas tareas, FP y FP2.

**Comment by toopazo** [comment]
Se reemplazo la llamada a "exeCmd.fnct = repo_getFunction(NewCmd.cmdId)" y se creo el comando drp_id_fpl_check_and_exec ya que esa llamada en un Listener reseteaba el Sw SUCHAI, por ello se desplazo esa llamada a un comando y que el executer la realizara.

**Comment by carlgonz** [comment]
Ok

*Carlos González Cortés.*
Ingeniero Civil Eléctrico
Universidad de Chile
+56975535716

2015-01-13 16:21 GMT-03:00 Tomas Opazo <notifications@github.com>:
